name: "Generate GitHub Stats SVGs"
description: "Generate SVG cards using leo-git-statistics and copy them to caller repository"

branding:
  icon: "bar-chart-2"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token used by generate.py (ACCESS_TOKEN)"
    required: true
  github-username:
    description: "GitHub username to generate stats for (defaults to github.actor)"
    required: false
    default: ""
  python-version:
    description: "Python version"
    required: false
    default: "3.11"
  output-dir:
    description: "Destination folder in caller repository"
    required: false
    default: "generated_images"
  config-path:
    description: "Path to config.yml in caller repository"
    required: false
    default: "config.yml"
  config-overrides:
    description: "YAML overrides merged into config at runtime"
    required: false
    default: ""
  static-api-data-dir:
    description: "Path to pre-generated static API JSON root (for example: api-data)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        pip install -r "${{ github.action_path }}/requirements.txt"

    - name: Prepare runtime config
      shell: bash
      env:
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
        INPUT_CONFIG_OVERRIDES: ${{ inputs.config-overrides }}
      run: |
        set -euo pipefail

        SRC_CONFIG="${{ github.workspace }}/${INPUT_CONFIG_PATH}"
        DST_CONFIG="${{ github.action_path }}/config.yml"

        if [ -f "${SRC_CONFIG}" ]; then
          cp -f "${SRC_CONFIG}" "${DST_CONFIG}"
        fi

        if [ -n "${INPUT_CONFIG_OVERRIDES}" ]; then
          export INPUT_CONFIG_OVERRIDES
          export DST_CONFIG
          python - <<'PY'
          import os
          import yaml

          config_path = os.environ["DST_CONFIG"]
          overrides_raw = os.environ["INPUT_CONFIG_OVERRIDES"]
          overrides = yaml.safe_load(overrides_raw) or {}

          with open(config_path, "r", encoding="utf-8") as fh:
              base = yaml.safe_load(fh) or {}

          def deep_merge(dst, src):
              for key, value in (src or {}).items():
                  if isinstance(value, dict) and isinstance(dst.get(key), dict):
                      deep_merge(dst[key], value)
                  else:
                      dst[key] = value

          deep_merge(base, overrides)

          with open(config_path, "w", encoding="utf-8") as fh:
              yaml.safe_dump(base, fh, sort_keys=False)
          PY
        fi

    - name: Generate SVGs
      shell: bash
      env:
        ACCESS_TOKEN: ${{ inputs.github-token }}
        INPUT_GITHUB_USERNAME: ${{ inputs.github-username }}
        FALLBACK_GITHUB_ACTOR: ${{ github.actor }}
        INPUT_STATIC_API_DATA_DIR: ${{ inputs.static-api-data-dir }}
      run: |
        set -euo pipefail

        ACTOR="${INPUT_GITHUB_USERNAME}"
        if [ -z "${ACTOR}" ]; then
          ACTOR="${FALLBACK_GITHUB_ACTOR}"
        fi
        export GITHUB_ACTOR="${ACTOR}"

        if [ -n "${INPUT_STATIC_API_DATA_DIR}" ]; then
          export STATIC_API_DATA_DIR="${INPUT_STATIC_API_DATA_DIR}"
        fi

        cd "${{ github.action_path }}"
        python generate.py

    - name: Copy SVGs to caller repository
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "${{ github.workspace }}/${{ inputs.output-dir }}"
        cp -f "${{ github.action_path }}/generated_images/"*.svg "${{ github.workspace }}/${{ inputs.output-dir }}/"
