"""
Segregated Protocol definitions for stats providers and infrastructure.

Defines narrow interfaces so each generator depends only on the
subset of statistics it actually uses.
"""

from typing import Dict, Any, Set, Tuple, Protocol, runtime_checkable


@runtime_checkable
class StreakProvider(Protocol):
    """
    Provides streak and total contribution statistics.

    Used by :class:`StreakGenerator`.
    """

    async def get_current_streak(self) -> int: ...
    async def get_longest_streak(self) -> int: ...
    async def get_current_streak_range(self) -> str: ...
    async def get_longest_streak_range(self) -> str: ...
    async def get_total_contributions(self) -> int: ...


@runtime_checkable
class BatteryProvider(Protocol):
    """
    Provides streak and recent contribution data for battery visualization.

    Used by :class:`StreakBatteryGenerator`.
    """

    async def get_current_streak(self) -> int: ...
    async def get_longest_streak(self) -> int: ...
    async def get_current_streak_range(self) -> str: ...
    async def get_longest_streak_range(self) -> str: ...
    async def get_recent_contributions(self) -> list: ...


@runtime_checkable
class LanguageProvider(Protocol):
    """
    Provides programming language statistics.

    Used by :class:`LanguagesGenerator` and :class:`LanguagesPuzzleGenerator`.
    """

    async def get_languages(self) -> Dict[str, Any]: ...


@runtime_checkable
class OverviewProvider(Protocol):
    """
    Provides general overview statistics for the profile card.

    Used by :class:`OverviewGenerator`.
    """

    async def get_name(self) -> str: ...
    async def get_stargazers(self) -> int: ...
    async def get_forks(self) -> int: ...
    async def get_views(self) -> int: ...
    async def get_clones(self) -> int: ...
    async def get_total_contributions(self) -> int: ...
    async def get_lines_changed(self) -> Tuple[int, int]: ...
    async def get_avg_contribution_percent(self) -> str: ...
    async def get_repos(self) -> Set[str]: ...
    async def get_collaborators(self) -> int: ...
    async def get_contributors(self) -> Set[str]: ...
    async def get_pull_requests(self) -> int: ...
    async def get_issues(self) -> int: ...
    async def get_views_from_date(self) -> str: ...
    async def get_clones_from_date(self) -> str: ...
